### ISSUE TITLE
Alternative to PEG.js

### ISSUE THREAD

**Issue by stefanos82** [livebud/duo#1]
Interesting enough, I have found https://github.com/mna/pigeon by pure accident a while ago!

From its README page we read the following:

> # pigeon - a PEG parser generator for Go
> The pigeon command generates parsers based on a [parsing expression grammar (PEG)](http://en.wikipedia.org/wiki/Parsing_expression_grammar). Its grammar and syntax is inspired by the [PEG.js project](http://pegjs.org/), while the implementation is loosely based on the [parsing expression grammar for C# 3.0](http://www.codeproject.com/Articles/29713/Parsing-Expression-Grammar-Support-for-C-Part) article. It parses Unicode text encoded in UTF-8.

I first learned about PEG from Lua's creator with his project [LPeg](http://www.inf.puc-rio.br/~roberto/lpeg/), but don't ask me much about language design and implementation lol!

**Comment by matthewmueller** [comment]
Thanks for the link. I'm actually aware of pigeon, but unfortunate it relies heavily on `interface{}` types. 

As a result, I prefer this one: https://pkg.go.dev/github.com/pointlander/peg

Neither are as powerful as PEG.js though. I'm hoping for some more innovation in this space now that generics are a thing :)
