### ISSUE TITLE
Svelte lexer

### ISSUE THREAD

**Issue by stefanos82** [livebud/duo#2]
I have found the following svelte lexer in case you are interested in studying it or even better, borrowing it (MIT License):

https://github.com/alecthomas/chroma/blob/master/lexers/svelte.go

**Comment by matthewmueller** [comment]
Sorry for the late reply here @stefanos82! Didn't get the notification for some reason. 

Thanks for the heads up! This would be a good start for a lexer, but I already wrote one :)
